export const customColors = {
  yellow: "Amarillo",
  gold: "Dorado",
  orange: "Naranja",
  brown: "Marrón",
  red: "Rojo",
  magenta: "Magenta",
  rose: "Rosa",
  crimson: "Carmesí",
  orchid: "Orquídea",
  lilac: "Lila",
  violet: "Violeta",
  purple: "Púrpura",
  iris: "Iris",
  cobalt: "Cobalto",
  blue: "Azul",
  turquoise: "Turquesa",
  mint: "Menta",
  kelly: "Kelly",
  green: "Verde",
  moss: "Musgo",
  gray: "Gris",
  platinum: "Platino",
  lichen: "Lichen",
  slate: "Pizarra",
};

export const bgCustomColors = {
  yellow: "bg-yellow",
  gold: "bg-gold",
  orange: "bg-orange",
  brown: "bg-brown",
  red: "bg-red",
  magenta: "bg-magenta",
  rose: "bg-rose",
  crimson: "bg-crimson",
  orchid: "bg-orchid",
  lilac: "bg-lilac",
  violet: "bg-violet",
  purple: "bg-purple",
  iris: "bg-iris",
  cobalt: "bg-cobalt",
  blue: "bg-blue",
  turquoise: "bg-turquoise",
  mint: "bg-mint",
  kelly: "bg-kelly",
  green: "bg-green",
  moss: "bg-moss",
  gray: "bg-gray",
  platinum: "bg-platinum",
  lichen: "bg-lichen",
  slate: "bg-slate",
};

export const borderCustomColors = {
  yellow: "border-yellow",
  gold: "border-gold",
  orange: "border-orange",
  brown: "border-brown",
  red: "border-red",
  magenta: "border-magenta",
  rose: "border-rose",
  crimson: "border-crimson",
  orchid: "border-orchid",
  lilac: "border-lilac",
  violet: "border-violet",
  purple: "border-purple",
  iris: "border-iris",
  cobalt: "border-cobalt",
  blue: "border-blue",
  turquoise: "border-turquoise",
  mint: "border-mint",
  kelly: "border-kelly",
  green: "border-green",
  moss: "border-moss",
  gray: "border-gray",
  platinum: "border-platinum",
  lichen: "border-lichen",
  slate: "border-slate",
};

export const hexCustomColors = {
  yellow: "#ffb900",
  gold: "#ff8c00",
  orange: "#f7630c",
  brown: "#ca5010",
  red: "#d13438",
  magenta: "#e81123",
  rose: "#e74856",
  crimson: "#c30052",
  orchid: "#e3008c",
  lilac: "#b146c2",
  violet: "#8764b8",
  purple: "#9a0089",
  iris: "#6b69d6",
  cobalt: "#0078d7",
  blue: "#0099bc",
  turquoise: "#00b7c3",
  mint: "#018574",
  kelly: "#10893e",
  green: "#107c10",
  moss: "#498205",
  gray: "#7a7574",
  platinum: "#69797e",
  lichen: "#486860",
  slate: "#515c6b",
};

export const textCustomColors = {
  yellow: "text-yellow",
  gold: "text-gold",
  orange: "text-orange",
  brown: "text-brown",
  red: "text-red",
  magenta: "text-magenta",
  rose: "text-rose",
  crimson: "text-crimson",
  orchid: "text-orchid",
  lilac: "text-lilac",
  violet: "text-violet",
  purple: "text-purple",
  iris: "text-iris",
  cobalt: "text-cobalt",
  blue: "text-blue",
  turquoise: "text-turquoise",
  mint: "text-mint",
  kelly: "text-kelly",
  green: "text-green",
  moss: "text-moss",
  gray: "text-gray",
  platinum: "text-platinum",
  lichen: "text-lichen",
  slate: "text-slate",
};

export type CustomColor = keyof typeof customColors;
